### ISSUE TITLE
Spis poziadaviek

### ISSUE THREAD

**Issue by richnak2** [TIS2020-FMFI/time-slot#11]
Pls sprav hrubi spis poziadviek s callu a zachit tam aj nase pripomienky

**Comment by davidvach** [comment]
Zostáva:

* štylizácia
* doplnenie požiadaviek na základe druhého meetingu
* overenie zadávateľom

**Comment by pavelpetrovic** [comment]
Dobrý deň, neviem či ste niečo menili v poslednom čase, ale verziu, ktorú som dostal od Ondreja som okomentoval a prikladám. Je to ešte len polotovar, treba to ešte poriadne vylepšiť, ale je to na dobrej ceste.
[Supis_Poziadaviek_s_komentarmi.docx](https://github.com/TIS2020-FMFI/time-slot/files/5412502/Supis_Poziadaviek_s_komentarmi.docx)

**Comment by richnak2** [comment]
https://docs.google.com/document/d/1LlogcV4jOUYINv5XQph6AhoASA0hCxEoijKktekGQfY/edit?usp=sharing 

Vyjadrenie k vami poslanemu suboru.

1.Kezde sa jedna o aplikaciju ktora len rezervuje niake datumi a neni specifikovana internim slovnikom tak nam netreba "slovník pojmov "
2.Rating o ktorom piseme je na zaklade Poziadaviek zadavatela 'nechcu rating 0-5' chcu priamo "prisiel / neprisiel"
3. Centalni admin je odstraneni 
4. Po usporiadni vsetkch poziadviek chronologicky sme dosiahli rozdelenie funkcnich a disignovich poziadviek.

@pavelpetrovic 

Dobry den prosim skontrolujte . Dakujeme

**Comment by pavelpetrovic** [comment]
Dobrý deň, ďakujem za mierne úpravy. Dokument ste stále zanechali v šialenom stave, bol to jeden veľký zmätok. Pokúsil som sa to upratať ako som vedel podľa toho, ako som to pochopil, takže to teraz zasa skúste poupravovať ďalej Vy, ak je to ešte potrebné a ak tam niečo nesedí s tým, aké máte informácie. Snažil som sa Vám to tam trochu zjednodušiť, aby to bolo čo najmenej práce, ale zároveň robilo všetko, čo podľa mňa zadávateľ potrebuje. Pošlite mi to, prosím, ešte raz na rýchlu kontrolu, keď to budete mať všetci pozreté a poupravované.
