### ISSUE TITLE
Skontaktovanie s IT department 

### ISSUE THREAD

**Issue by richnak2** [TIS2020-FMFI/time-slot#19]
Prosim dohodni sa s GEFKO a daj nam vediet sem ako sme dopadli a kedy budu stretavky dakujem

**Comment by richnak2** [comment]
IT manažér Ján Šifta
jan.sifta@gefco.net

**Comment by richnak2** [comment]
Nove info po vyse tyzdni od poslania E-mailu som nedostal vyjadrenie k e-mailu ...

**Comment by pavelpetrovic** [comment]
včera či predvčerom som s nimi krátko hovoril, vraveli, že ten mailový server bude microsoft exchange...
na internete je mnozstvo clankov o tom, ako pripravit skripty pre exchange na spracovanie mailov
idealne by teda bolo, keby ten skript dokazal odovzdat prijaty mail nejakemu Vasmu programu, ktory bude nahraty na tom exchange mailovom servri a vytiahol z neho udaje hned pri doruceni a ulozil ich do databazy.
ked som sa technika opytal, ci taketo riesenie by prichadzalo do uvahy, tak sa tvaril, ze zrejme hej, ale ze on o tom nic nevie. skuste pohladat a pripadne hned aj vyskusat takuto moznost. exchange sa urcite da nakonfigurovat aj na to, aby prijimal maily z nejakeho testovacieho gmail uctu a podobne.
