### ISSUE TITLE
UML

### ISSUE THREAD

**Issue by richnak2** [TIS2020-FMFI/time-slot#20]
Treba vytvorit vsetky UML diagrami  priadajte ich na koniec dokumentu 

https://docs.google.com/document/d/1LlogcV4jOUYINv5XQph6AhoASA0hCxEoijKktekGQfY/edit

zatial je tu moznnost vyberu ktori bude robit aky Napiste pod tento prispevok coment ktori si beriet na starosti aby nedoslo k duplicitnej vyrobe !

**Comment by davidvach** [comment]
UML class diagram

**Comment by richnak2** [comment]
UML class diagram

**Comment by Timotej12** [comment]
State diagram

**Comment by Sis-si** [comment]
Component diagram

**Comment by pavelpetrovic** [comment]
dostal som novu verziu class diagramu cez teams:
* skuste sa drzat jedneho jazyka :-), vidim tam slovencinu aj anglictinu, preferujem v nazvoch identifikatorov, tabuliek a pod. anglictinu, lebo pri softveri clovek nikdy nevie, ci s tym o rok nebude pracovat napr. nejaky Rumun, alebo Spaniel
* trieda Gate sa nam zredukovala na jeden int? tak ju mozeme zlucit s triedou Calendar a napriklad nazvat GateCalendar
* nesedi mi relacia medzi kamionista a truck, pretoze v kamionistovi je id_truck, ale ma to byt relacia 1:N
* nerozumiem vztahu user - role  1:1, na co vobec sluzi trieda role? nestacil by atribut role v triede user? obsahoval by vymenovany typ - jednu zo styroch moznych hodnot admin/externy/interny/vratnica?
* v timeslote by asi este mohlo byt nejake datetime, ze kedy ten timeslot zacina

**Comment by richnak2** [comment]
Dobry den uz sme tam porobili zopar zmien verim ze je to fine . Zmenili sme sposob asociacie trucku s time-slotom pre odlahcenie mnozstva dat v db.

https://drive.google.com/file/d/1u6NAFlJdK-cpVf_6PQ2VFaQ5Zc5LzNLd/view?usp=sharing

Ak su niake pripomienky ozvite sa . Dakujem @pavelpetrovic

**Comment by pavelpetrovic** [comment]
* cize id_truck_driver v TimeSlot je kolekcia?
* v tom pripade by sa mohla volat nejak truck_drivers_ids - a teda rozumiem dobre, ze su vsetci vodici rovnocenni, alebo je tam niektory hlavny?
* state poskocil na predch. riadok :)
* v time-slote budete asi potrebovat nieco ako "reservation-expiration", ale to uz su implementacne detaily, zatial ich tam asi netreba kreslit
* task_evnet  -> event

**Comment by Timotej12** [comment]
Dobrý deň ,upravil som State diagram podľa vaších požiadaviek.
Link: https://drive.google.com/drive/folders/1STWufWlZ3-x-e_XODb3Xp6ZK6XBbAr5b
Ak by boli nejaké pripomienky tak sa ozvite. Dakujem @pavelpetrovic

**Comment by davidvach** [comment]
@pavelpetrovic opravili sme v [UML class diagrame](https://drive.google.com/file/d/1y6hWPw3lMjkcfF_LgiB9_RjUw60mL9n0/view?usp=sharing) najnovšie preklepy a nedostatky (`id_truck_driver` je naozaj kolekcia, v ktorej sú všetci vodiči z pohľadu projektu rovnocenní, takže sme ju premenovali na `truck_driver_ids`).

**Comment by Sis-si** [comment]
Pridávam link na diagramy.
https://drive.google.com/drive/folders/1STWufWlZ3-x-e_XODb3Xp6ZK6XBbAr5b

Pribudla tam nová verzia Component Diagram.

**Comment by Sis-si** [comment]
Diagram OK.
Treba pridať popis ku Component Diagramu.

**Comment by richnak2** [comment]
4.12.2020 rozhovor Teams s ucitelom 3h:26minuta  pre  popis ku Component Diagramu.

**Comment by Sis-si** [comment]
4.12.2020 Pravidelné stretnutie sa s učiteľom pomocou aplikácie Teams - nahrávka, čas 3:31:17 pre popis ku **všetkým** diagramom.

**Comment by Sis-si** [comment]
Pridaný popis ku Component diagramu.

**Comment by davidvach** [comment]
Všetky diagramy sú hotové a nahrané v [**súpise požiadaviek**](https://docs.google.com/document/d/1LlogcV4jOUYINv5XQph6AhoASA0hCxEoijKktekGQfY/edit?usp=sharing) v časti 5.4.

**Comment by pavelpetrovic** [comment]
dali ste, prosím, zadávateľom k dispozícii aj tú stručnú príručku so screenshotmi, aby to podľa toho mohli používať?

**Comment by davidvach** [comment]
@pavelpetrovic áno, [manuál](https://drive.google.com/file/d/1qMHSSMHi5Z9R1gU63ZARBaiVA07dN2my/view?usp=sharing) k aplikácii sme zadávateľom posielali mailom.

**Comment by pavelpetrovic** [comment]
fajn, pridajte ho, prosím, priamo na github, kde máte aj ostatnú dokumentáciu.
