### ISSUE TITLE
Navrh pouzivatelskeho rozhrania

### ISSUE THREAD

**Issue by richnak2** [TIS2020-FMFI/time-slot#21]
https://drive.google.com/drive/folders/1STWufWlZ3-x-e_XODb3Xp6ZK6XBbAr5b?usp=sharing

**Comment by davidvach** [comment]
Návrh je hotový, zostáva odkonzultovať ho so zadávateľom.

**Comment by richnak2** [comment]
Ja si mislim ze uz je navrh ozaj vo finalnej verziji a netreba uz viacej diskutovat o tom ako ma prostredie vyzerat. Tim padom zatvaram tento issiue . pokial nastanu dalsie zmeni v dizajne a nieco nebude este nutne menit tak bude znovu otvoreni
