### ISSUE TITLE
navrh datoveho modelu model 

### ISSUE THREAD

**Issue by richnak2** [TIS2020-FMFI/time-slot#22]
1. perzistentných údajov 
2.  formátov súborov
3.  komunikačných protokolov

**Comment by davidvach** [comment]
...
2. formátov súborov
3. komunikačných protokolov

**Comment by davidvach** [comment]
Návrh dátového modelu je hotový a nahraný v [**súpise požiadaviek**](https://docs.google.com/document/d/1LlogcV4jOUYINv5XQph6AhoASA0hCxEoijKktekGQfY/edit?usp=sharing) v časti 5.1 - 5.4.
