### ISSUE TITLE
Rozdelenie úloh implementácie

### ISSUE THREAD

**Issue by davidvach** [TIS2020-FMFI/time-slot#28]
**Organizácia na Githube:** Keď niekto vytvára novú funkciu / rozširuje existujúci kód, vytvorí si na Githube novú branch-u, ktorú nazve podľa problému, ktorý ide riešiť (napr. ide rozšíriť zamestnancov o možnosť editovanie ich dát, tak si nazve branch-u `zamestnanci_edit_data`). V tej chvíli má nová branch všetky dáta z master-u (ktorý považujeme, že jeho dáta sú korektné a funkčné) a môže vytvárať nový kód.
Po rozšírení, v prípade že funkcionalita je korektná a funguje, zmerguje svoju branch s mastrom, v opačnom prípade branch zahodí (o žiadne predtým funkčné dáta sa takto neprišlo, pretože sú stále v nezávislej branchi master).

Problémy, ktoré môžu nastať:
  * pri tvorbe kódu je zakázané pull-ovať nové dáta z mastru, lebo sa stratí pôvodný kód (z vami vytvorenej branch-e)
  * po úspešnom mergi s masterom, si môžte pull-núť dáta, pokiaľ chcete pokračovať na danej branchi
  * pokiaľ bol merge úspešný a pokračujete v commitoch, tak nemôžte pull-núť mastera, inak znovu strácate dáta

**Pred začiatkom práce na novej funkcii je potrebné vytvoriť príslušnú issue na Githube!**

## Zoznam hlavných úloh:

Číslo | Úloha | Prerekvizita
------------ | ------------- | -------------
1 | ~~Funkcionalita stránky zamestnancov - pridávanie, editovanie údajov~~ |
2 | ~~Prihlasovacia stránka - prihlásenie do systému~~ | 
3 | ~~Stránka so zmenou hesla, tlačidlo potvrdenia zmeny, zmena hesla v databáze~~ | 
4 | ~~Zobrazenie obsahu kalendáru ku zvolenému dňu~~ | 
5 | ~~Pripravenie tabuľky v databáze pre TimeSlot, export `sql` kódu~~ | 
6 | ~~Pripravenie tabuľky v databáze pre GateCalendar, export `sql` kódu~~ | 
7 | ~~Pripravenie tabuľky v databáze pre Truck, export `sql` kódu~~ | 
8 | ~~Pripravenie tabuľky v databáze pre TruckDriver, export `sql` kódu~~ | 
9 | ~~Pripravenie tabuľky v databáze pre EventLog, export `sql` kódu~~ | 
10 | ~~Vytvorenie insert `sql` skriptu s abstraktnými (testovacími) dátami pre TimeSlot, obsahom bude 5000 vytvorených time-slotov (s rôzne zvolenými stavmi (`booked`/`prepared`/`requested`)), s počiatočným dátumom spustenia skriptu na nasledujúcich 5 dní~~ | 5
11 | ~~Stránka vrátnika - fungovanie search-boxu "Find by"~~ | 10
12 | ~~Stránka vrátnika - fungovanie tlačidla "Potvrdiť", správne fungovanie metódy pre potvrdenie~~ | 10
13 | ~~Stránka vrátnika - korektné zobrazenie dostupných time-slotov k ich časom (zohľadňujúc administrátorom nastavenú~~ konštantu meškania) | 10
14 | ~~Stránka kontaktných informácií - s využitím Bootstrap-u~~ | 
15 | ~~Stránka objednávky - korektné zobrazenie pre externého dispečera a interného dispečera / admina~~ | 2
16 | ~~Stránka objednávky - fungovanie časovača pre meranie času od zobrazenia stránky externým dispečerom, nastaveným na 10 minút~~ | 15
17 | ~~Stránka objednávky - fungovanie tlačidiel "Verify", "Edit", "Delete", "Create"~~ | 
18 | ~~Stránka zamestnancov - fungovanie select boxu "Select only"~~ | 1
19 | ~~Stránka zamestnancov - fungovanie search boxu "Find by"~~ | 1
20 | ~~Fungovanie tlačidla odhlásenia používateľa~~ | 2
21 | ~~Stránka kalendáru - fungovanie search boxu "Find by", vyznačenie nájdeného time-slotu~~ | 10
22 | ~~Stránka kalendáru - pridanie funkcionality šípkam pri kalendári a samotnému mini-kalendáru na výber dátumu zobrazenia (`onchange`/`onclick` event)~~ | 10
23 | ~~Prihlasovacia stránka - pri prvom načítaní stránky užívateľom (`login_count == 0`) presmerovanie stránku zmeny hesla~~ | 2

## Zoznam úloh pre výpisy chýb ("alerts"):

Číslo | Úloha
------------ | -------------
24 | ~~Zamestnanci - ošetrenie pri zmeny role~~
25 | ~~Zamestnanci - ošetrenie zmeny check boxu "is working"~~
26 | ~~Zamestnanci - ošetrenie zmeny mena~~
27 | ~~Zamestnanci - ošetrenie zmeny priezviska~~
28 | ~~Zamestnanci - ošetrenie zmeny emailovej adresy~~
29 | ~~Objednávka - oboznámenie o vypršanom čase pri zadávaní objednávky~~
30 | ~~Objednávka - oboznámenie interného dispečera / administrátora o zmene vykonanej na danom time-slote~~
31 | ~~Objednávka - oboznámenie externého, interného dispečera / administrátora o zmazaní time-slotu~~
32 | ~~Zmena hesla - oboznámenie užívateľa o zmene hesla (napr. pre nedostatočnú dĺžku alebo nesprávne zadanie údajov)~~

## Prevencia voči SQL injection:

Číslo | Úloha
------------ | -------------
33 | ~~Ošetrenie správneho zobrazenia voči roliam užívateľov~~
34 | ~~Ošetrovanie vstupov od užívateľa~~

## Enkapsulácia programu do tried JavaScriptu:

Číslo | Úloha | Prerekvizita
------------ | ------------- | -------------
35 | ~~Samostatná enkapsulácia do .js~~ |
36 | ~~Vygenerovanie hlavičky podľa roly používateľa~~ | 35
37 | ~~Vygenerovanie elementu navigácie podľa roly používateľa~~ | 35

## Zoznam úloh vzniknutých v procese vytvárania:
Priebežne dopĺňané členmi tímu.

Číslo | Úloha | Prerekvizita
------------ | ------------- | -------------
38 |~~nova implementacia kalendaru podla zistenich potrieb zadavatela (wiki 11.11.2020)~~ |
39 | ~~Zmena na stranke zamestnanci , pridanie buttonu edit , spravit desiable inputs~~ |
40 | ~~Pridanie "tooltipu" pre search-box "Find By" na stránke interného dispečera~~ |
41 | ~~Pridanie stavu `.disabled` pre príslušné tlačidlá na stránkach interného a externého dispečera~~ |
42 | ~~Pridanie zobrazovania dát vo farebných time-slotov (okrem stavu daného time-slotu aj údaje ako meno dispečera a mená vodičov), odstrániť `.css` nad a pod riadkami stĺpcov (2px)~~ |
43 | ~~Po rozkliknutí konkrétneho time-slotu z kalendáru sa korektne zobrazia stavy `prepared`, `requested`, `booked`, `finished` (usporiadať si v phpmyadmin podľa `start_time` a skontrolovať, či daný time-slot odpovedá dátam HTML (`objednavka.php`))~~ |
44 | ~~Bootstrap bol stiahnutý do súboru, teraz treba pomeniť navigáciu tak, aby bola všade jednotná, stiahnuť aj JQuery Ajax do priečinka a následne upraviť rovnako ako v prípade Bootstrap-u (viď. IND, EXD)~~ |
45 | ~~Funkcionalita čítania time-slotov iba od `start_time == NOW()` a `end_time == NOW() + 7 pracovných dní~~ |
46 | ~~Optimalizácia kalendáru tak, aby sa zobrazoval až od času 6:00 (čo je začiatok pracovného času)~~ |
47 | Treba ešte dokončiť OOP na niektoré funkcie, ktoré sú rovnaké na obidvoch stránkach IND a EXD |
48 | ~~Treba pridať tlačidlo "Disable" k IND ku každej rampe, ktoré odstráni všetky time-sloty na daný deň a danú rampu~~ |
49 | ~~Pridanie funkcionality tlačidiel "Show" pre IND a EXD~~ |
50 | ~~Pridanie stranky a tabulky na ovladanie generovania time slotov a pridavania prazdnin 3 stlpce start time  , end time , prepisat  svitok~~  |
51 | ~~implementacia tohto formatu do uz vytvoreneho generate_script_deffoult.php~~ | 50
52 | ~~vytvorenie dump sql scritu ktori bude data uchovavat v DB na dobu neurcitu~~ | 
53 | ~~POZOR tato zmena bude menit vsetky ajaxi,sql prikazi,javaskrity - pridanie zobrazenia -7 +7 dni v kalendari pre  EXD  a pre IND je to zmena len -7   --> 45 neplati teda ju skrtam~~ |
54 | ~~zmena všetkých ext. dispečer za dopravcu (spoločnosť)~~ |
55 | ~~pridanie odstavenia rampi na do config stranky~~ |
56 | ~~odstranenie duplikovania dat pokial je aktivovana funkcia regenerate time slot v config file~~ |
57 | ~~Pridanie obmedzenia dlzky vypisov v calendari pre IND {menosplocnosti/destination/evc: ,max 12znakovcargo: max 3-30znakov }~~  | |
58 | ~~Treba pridat priami prisup k "requested" time slotom zo stranky internal_dispatcher.php~~ |
59 | Zjednotenie datumov na svk format | 
60 | ~~Zjednotenie zobrazovania navigácie podľa EXD pre všetky stránky~~ | 
61 | ~~spravenie update mechanizmu pre vsetkich userov EXD , IND/AD ,  GM na im prislusnim strankam~~ | 
62 | ~~Treba pridat automaticky script ktori updatne vsetky occupied time sloti ktore su neni v casoch occupied_strat_time a occupied_end_time -> osetrenie ak niekto len zatvori okienko a neukonci objednavku~~  |
63 | Odstranenie CSS s HTML | 
64 | | 

Do komentárov priebežne dopĺňajte úlohy, na ktorých budete pracovať.

**Comment by richnak2** [comment]
Ja idem robit 1 code je pod issiue #26

**Comment by davidvach** [comment]
2, 23 (kód je pod issue #25)

**Comment by richnak2** [comment]
3 (kód je pod issue #32)

**Comment by Timotej12** [comment]
5,6,7,8,9 (kod je pod issue #33 )

**Comment by richnak2** [comment]
20 (kód je pod issue #32) - potrebujem funkcni session tak dorbim log out button pre zrusenie session , cize zmenim par dat aj v calendari (.php) a pridam niky ten js kodik a tak proste pohoda a dzez :D ked niekto bude chciet riesit pomedzi tak dajte vediet aby som nepokazil validiu vasho kodu .

**Comment by Sis-si** [comment]
14 - kód je pod issue #35

**Comment by davidvach** [comment]
18, 19 (kód je pod issue #37)

**Comment by richnak2** [comment]
39(kód je pod issue #40)

**Comment by davidvach** [comment]
10 (kód je pod issue #40)

**Comment by richnak2** [comment]
4,42,21 (kód je pod issue #40)

**Comment by Sis-si** [comment]
44 - kód je pod issue #43

**Comment by davidvach** [comment]
15, 16, 17, 49 (kód je pod issue #44)

**Comment by Timotej12** [comment]
11,12,13 (kód je pod issue #45)

**Comment by Sis-si** [comment]
50, 51 (kód je pod issue #47)

**Comment by davidvach** [comment]
41 (kód je pod issue #52)

**Comment by richnak2** [comment]
33 36 37 (kód je pod issue #54)

**Comment by Sis-si** [comment]
54, 58 (kód je pod issue #55)

**Comment by davidvach** [comment]
55, 56 (kód je pod issue #60)

**Comment by richnak2** [comment]
celi block allerts + drobnosti #66

**Comment by davidvach** [comment]
Úlohy, ktoré zostali nepreškrtnuté, sú súčasťou finálnych úloh v issue [**Rozdelenie finálnych úloh**](https://github.com/TIS2020-FMFI/time-slot/issues/68).
