### ISSUE TITLE
Testovacie scenare

### ISSUE THREAD

**Issue by richnak2** [TIS2020-FMFI/time-slot#29]

**Comment by Sis-si** [comment]
Pridať testovacie scenáre do tohto dokumentu.

https://docs.google.com/document/d/1LlogcV4jOUYINv5XQph6AhoASA0hCxEoijKktekGQfY/edit

**Comment by davidvach** [comment]
Všetky scenáre sú hotové a nahrané v [**súpise požiadaviek**](https://docs.google.com/document/d/1LlogcV4jOUYINv5XQph6AhoASA0hCxEoijKktekGQfY/edit?usp=sharing) v časti 7.
