### ISSUE TITLE
Nový front-end stránky

### ISSUE THREAD

**Issue by davidvach** [TIS2020-FMFI/time-slot#40]
Nový front-end stránky pre interného a externého dispečera.

**Comment by richnak2** [comment]
1. Prosim pozrite si kod Vsetci , pod pojmom IND a EXD rozumieme calenare a ich zobrazenia 
2. David pozri calendar AJAX/generate_script.php mal by byt uz vo finalnej verziji aj s validnimi datami  ak bude ok vykrtni to zo zoznamu dakujem mozes to pridat aj ako vlastni prvok implementacie lebo bez teba bi to neslo ... Dakujem
3. Zmena stranky IND  , zmena stranky EXD , zmena celkovej logiky SQL 
4. pre IND : 3 moznosti zobrazenia  neni tam tool typ prosim pridat do issiu a do uloh ako daky 40 bod 
5. pre IND : Vsetky buttonni funguju prosim skontroluje ci to ide aj vam pokial nie problem rieste sami ale informujete na gite s chybami (pozerajete console.log() na stranke )
6. pre IND a EXD: treba pridat  .disabled na buttoni ktorim to prislucha (datumi a gate selector) prosim spravte dalsiu ulohu ako daky 41 bod 
7. pre IND : treba dodat do danich farbnich row & column data ako su meno dispecera a mena vodicov (pre niektore stlce a riaky sa to bude prekrivat to nerieste ps. generovane data su na 85%schopne validiti ), css treba odstanit _ _ _ _ (2px dsah ) nad a pod riadkami stlpov kde nemaju byt . Prosim spravte dalsiu ulohu ako daky 42 bod 
7. pre IND a EXD : treba pridat otvaranie time_slotov SPAVICH ktore odpovedaju danumu HTML nemusite riesit komu sa to zobrazuje hlavne ze sa vam zobrazi spravni a spravne data to znamena zmena stranky objednavky a EXD a IND . Prosim spravte dalsiu ulohu ako daky 43 bod 
8. pre GLOBAL : bol stiahnuti bootstap do file , treba pomenit vsade  navigaciu aby bola jednotna , treba stiahnut aj jqueri ajax ako precinok a nasledne treba upravit tak isto ako s BOOTSTRAPOM , vid IND a EXD 
9. Pokial najdete ze nieco som nespomenul mozte upravit tento prispevok o to co som zabudol, pokial sa jedna aj o implementacu zalezitost pridajte tam aj daky abstraktni bod(napr. 45) kotoremu bude dana uloha zodpovedat .
10. pokial ste sa docitali az sem daj like na tento commit a napis svoj nazor , pripadne pridaj jeden s tychto bodou (alebo vsetky ) do "Rozdelenie úloh implementácie" pripadne si rovno zarezevuj ulohu na ktoru sa ides vrhnut kedze dana problematika sa po vecinu casu deje na jednej strake bud opatrni !!! Dakujem a vela zdaru pri kodeni teraz je cas na vas .

**Comment by davidvach** [comment]
1, 2, 3 - ok
4, 6, 7 - pridané do úloh
5 - fungujú okrem Kalendár - šípky vľavo vpravo na posúvanie zobrazenia rámp, "Log Out" z ostatných stránok, "Edit" a "Apply" na EXD
8 - pridaná do úloh (ako č. 43, pre istotu si ju prečítaj, nie som si istý či som ten problém správne pochopil)

**Comment by richnak2** [comment]
dodaok k bodu 8 - 43 uloha mam namisli REQUESTED , PREPARED , BOOKED a FINISHED aby boli po kliknui zobrazne tie spravne co to znamena ze si musite v phpmyadmin spravit usporiadanie podla "start_time" a nasledne skontrolovat ci dani time slot odpoveda datam HTML (objednavka.php)

**Comment by davidvach** [comment]
Posledne pridané veci:

1. Zapracovanie OOP
2. Premenovanie viacerých premenných
3. Odstránenie duplicít
4. Pridanie komentárov k nejasným častiam kódu
4.1. Komentáre k funkciám
```
/**
*
*@param XYZ - description : typ 
*/
```
4.2. Komentáre pre nejasné premenné
5. Jednotné pomenovania súbory (každá stránka sa volá podľa zodpovedajúceho užívateľa)
6. Úprava css v `external_dispatcher.css`
7. Premenovanie a úprava css v `main_page.css` -> `internal_dispatcher.css`
// poznámka EXD == external_dispatcher.php
// poznámka IND == calendar.php -> internal_dispatcher.php
8. EXD - Oprava názvov Employee -> Truck drivers
9. EXD, IND (Find by) - Pridanie stĺpcov Destination a Commodity (tovar)
10. IND - Oprava významu Employee = external dispatcher name (predtým bolo truck drivers)
11. Oprava sql  - pridanie tabulky "destination_order" {"id" ,"destination" , "commodity"}
12. Oprava sql  - pridanie spojenia (column) medzi tabulkami "time_slot" {"id_destination_commodity"} odkazujúcej sa na  "destination_order" {"id"}
13. Oprava generate_script.php -> generate_script_random.php, kedy sa generujú dáta aj nahodnými možnosťami nákladov
14. Oprava generate_script.php -> generate_script_deffoult.php, kedy sa generujú `prepared` time-sloty podľa obrázku zaslaného zadávateľom
15. Oprava IND (Find by) - zmena hľadania medzi všetkými dátumami, keďže prebieha cez veľa time-slotov, dochádza k chvíľkovému zasekávaniu (je tam citeľný lag pri písaní)
16. Oprava EXD (mini-kalendár) - možnosť posúvania sa iba v rámci nasledujúcich 7 dní (ak užívateľ dôjde na ich koniec, hodí ho to na začiatok) 
17. IND - úprava kalendáru voči písanému dátumu, pokiaľ je nesprávny (teda `mini_calendar_date` < `TODAY`), funkcia je zatiaľ zakomentovaná, treba ju ešte doriešiť
18. Týmto bola vyriešená úloha č. 42
19. Keďže "Find By" funguje inak, bola vyriešená úloha č. 21 
20. Keďže kalendár považujeme za funkčný, bola vyriešená úloha č. 4

Zostáva:
1. Funkcionalita čítania iba od `start_time` == `NOW()` a `end_time` == `NOW() + 7 pracovných dní` 
2. Optimalizácia kalendáru tak, aby sa zobrazoval až od 6:00 (čo je začiatok pracovného času) 
3. Treba ešte dokončiť OOP na niektoré funkcie, ktoré sú rovnaké na obidvoch stránkach IND a EXD

**Comment by richnak2** [comment]
Kedze komunikacia s dovatelmi do-konvergovala  to niecoho co mozme nazvat ako finalny stav noveho front endu tak tuto issiu uzatvaram.

Prosim o vijadrenie este ci som pouzil slovicko 'konvergovat' na spravnom ps je to len pre mna aby som si bol isti spravnosotou vyznamu a spravnosti pouzitia daneho slova dakujeeem :)
