### ISSUE TITLE
Rozdelenie finálnych úloh

### ISSUE THREAD

**Issue by davidvach** [TIS2020-FMFI/time-slot#68]
Tento zoznam obsahuje finálne úlohy, ktoré je potrebné vyriešiť po tom, čo budú implementované všetky funkcionality z issue [**Rozdelenie úloh implementácie**](https://github.com/TIS2020-FMFI/time-slot/issues/28).

## Zoznam úloh:

Číslo | Úloha | Prerekvizita
------------ | ------------- | -------------
1 | ~~Korektné zobrazenie stránky na mobilných zariadeniach~~ | 
2 | ~~Korektné zobrazenie hlavičky stránky na IND, EXD a stránke zamestnancov~~ | 
3 | ~~Vyladenie všetkých textov v HTML / PHP tak, aby boli zrozumiteľne formulované a v jednotnom jazyku (EN)~~ | 
4 | ~~Prerobenie systému výnimiek v `order.js` tak, aby existovali pravidlá pre všetky zadávané vstupy v okne s objednávkou (pri time-slotoch typu `prepared`, resp. `requested` v príslušných funkciách `request_time_slot` resp. `update_requested_time_slot`)~~ | 
5 | ~~Testovanie prehliadačov - prehliadače Chrome a Edge sú ok, Firefox obsahuje zlé zobrazenia (najmä v oblasti hlavičky stránky), Safari zatiaľ nie je otestovaný~~ | 
6 | ~~Modrá žiarovka na stránke interného dispečera - po prejdení kurzorom sa zobrazí veľký tooltip obsahujúci screenshoty zo stránky a vysvetľujúce popisy fungovania jej častí (prístup k eventom prechádzania kurzorom je už implementovaný), využitie Z-indexu s vysokou hodnotou (aby sa tooltip zobrazil úplne navrchu)~~ | 
7 | ~~Čistý kód (najmä pri ošetrovaní chýb, duplicitných funkciách a ďalších)~~ | 
8 | ~~Odstránenie `css` z `HTML` (nie všetko sa dá odstrániť, pretože niektoré funkcie vyžadujú parametre z `css` (napríklad `display:"none"`))~~ | 
9 | ~~Vo finálnej verzii odstránenie vypisovania chýb z SQL (v rámci prevencie SQL injection) - v PHP~~ | 
10 | ~~Úprava PHP súborov do OOP~~ | 
11 | ~~Zamedzenie možnosti úpravy uplynulých time-slotov pre všetkých užívateľov (môžu si ho zobraziť pomocou tlačidla "Show", avšak nemôže ho nijak editovať)~~ | 
12 | ~~Testovanie testovacích scenárov~~ | 

## Zoznam úloh vzniknutých v procese dokončovania:
Priebežne dopĺňané členmi tímu.

Číslo | Úloha | Prerekvizita
------------ | ------------- | -------------
13 | ~~Text `echo 'Time-slot is currently <strong>occupied<strong>';` pri otvorení time-slotu musí byť nahradený konkrétnym varovaním (napr. že si ho pozerá niekto iný alebo čas bol zmenený (v takom prípade vypíše časový úsek `ocupide_start_time` a `ocupide_end_time`))~~ | 
14 |  |

**Comment by richnak2** [comment]
Mislim si ze mozem napisat za vsvetkych ze dneska sme odviedli celkom pekni kus robotky podla toho co som si napisal na papier by sme mali mat hotove nasledne veci 2,3,4,5,6,11,12 - len s casti ale este to skusime jeden krat zbenut susime ,13  pokial nesuhlasite tak napiste komentar

**Comment by richnak2** [comment]
Pozorovanie dnesneho testovana (2) zaver : 

zistene drobne chyby v loadingu niektorich ajax get requestov 
--> naskor je do dane oneskorenim poslanim dat so servera a tym padom vzika error na strane usera a data niesu nacitane

Mobilne zariadenia : 
samsug internet browser --> nevie implementovat javaskript tak ako ma nefunkcne zobrazenie , nespravne nacitanie stranok / nuplne nacitanie 

ostatne mobilne prehliadace priamo nezistena chyba v nicom maximalne nie uplne jasne a prehladne zobrazenie ale vramci moznosti a nasej schopnosti to povazujem za ok

Order time_slot --> pri skoceni casoveho limitu time slot ostava occupide a tim padom nieje spristupneni nikomu

**Comment by richnak2** [comment]
Task Scheduler FUNGUJE a je odtestovni , nuz je nutne presunut subori do pricinka nepristupneho  verejnosti  a znovu odtestovat.

**Comment by richnak2** [comment]
Pozicija skriptov bola upravena a odtestovana vyzera to ze to funguje.

**Comment by richnak2** [comment]
Zistenie jeden z Task Scheduler nefunguje (generovanie kalendaru na nasledovni tizden) funkcnost je sice spravna ale po uplinuti casu sa zmazal je nutne ho nahradit takim ktori sa bude vediet opakovat do nekonecna kazdu nedelu DOLEZITE !!!

**Comment by richnak2** [comment]
Pridanie Loga , Firma GEFCO pouziva .png LOGO !!! co prosiiim??!!! strasne neviem ako moze standardne fimra pouzivat logo s nestandardnim formatom !!! bola nutne vytvorit logo formatu .svg , ktore bolo vitvorene a implenentovane na stranke . 

Dalej uprava Login stranki na format loga firmi aby to vyzeralo dobre .

Pridanie Dump_day.vbs na server pre vydupovanie databazy kazdy den koli tomu ak nahodou sistem padne aby boli data zachovane. Nasledne nastavenie vsb do Task Scheduleru. verim ze to zajtra odtestujeme .

Chyba ktora bola na serveri je tiez odstranena ale budeme to blizsie skumat zajtra okolo 10.00
