### ISSUE TITLE
Video k aplikácii

### ISSUE THREAD

**Issue by davidvach** [TIS2020-FMFI/time-slot#84]

**Comment by davidvach** [comment]
Odkaz na vytvorené video s prezentáciou projektu:

https://drive.google.com/file/d/1DfwjJQ9p0FUYv06aTfH1xqj2-lUp9xJ5/view?usp=sharing

@pavelpetrovic

**Comment by pavelpetrovic** [comment]
ďakujem, video sa mi veľmi páči!!

p.s. v úvode by som asi zvolil trochu jemnejšiu formuláciu - nie že aké je to teraz zlé - lebo to zbytočne vrhá tieň na zadávateľa, že prečo to teraz takto robil, keď to robil tak, zle, radšej by som zvolil pozitívnejšie formulácie, že sa darí a preto sa obchod rozrastá a hodí sa im niečo, čo im môže ešte lepšie zorganizovať príjazdy a ušetriť tým drahocenný čas dispečerom. ale to len taký drobný komentár pre Vás, keď niečo podobné budete robiť nabudúce. 

ešte teda budem potrebovať nejaké uzavretie zo strany zadávateľov, že už viac testovať viac nevládzu. :)
